service: whatsnew

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  timeout: 20
  stage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  generator:
    handler: bin/generator
    events:
      - http:
          path: generate
          method: get
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true
      - schedule:
          rate: cron(0 4 * * ? *)
          enabled: true
      - schedule:
          rate: cron(0 8 * * ? *)
          enabled: true
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: true
      - schedule:
          rate: cron(0 16 * * ? *)
          enabled: true
      - schedule:
          rate: cron(0 20 * * ? *)
          enabled: true
  uploader:
    handler: bin/uploader
    events:
      - http:
          path: upload
          method: post
